//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myWebEntities : DbContext
    {
        public myWebEntities()
            : base("name=myWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LANGUAGE> LANGUAGEs { get; set; }
        public virtual DbSet<PROFILE> PROFILEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<SERVIZI> SERVIZIs { get; set; }
        public virtual DbSet<GRUPPO> GRUPPOes { get; set; }
        public virtual DbSet<vServiceGroup> vServiceGroups { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<vUserPermission> vUserPermissions { get; set; }
    }
}
