//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myWebEntities : DbContext
    {
        public myWebEntities()
            : base("name=myWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LANGUAGE> LANGUAGEs { get; set; }
        public virtual DbSet<PROFILE> PROFILEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<SERVIZI> SERVIZIs { get; set; }
        public virtual DbSet<GRUPPO> GRUPPOes { get; set; }
        public virtual DbSet<vServiceGroup> vServiceGroups { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<vUserPermission> vUserPermissions { get; set; }
    }
}
