//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVIZI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVIZI()
        {
            this.GRUPPOes = new HashSet<GRUPPO>();
        }
    
        public System.Guid ID_SERVIZIO { get; set; }
        public string ENDPOINT { get; set; }
        public string DESCRIZIONE { get; set; }
        public string FIRMA { get; set; }
        public bool IS_ENABLED { get; set; }
        public System.DateTime DATA_CREAZIONE { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public System.Guid ID_USER { get; set; }
        public string CODE { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPPO> GRUPPOes { get; set; }
    }
}
