//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class vServiceGroup
    {
        public string GRUPPO_SERVIZIO { get; set; }
        public string CODE { get; set; }
        public string ENDPOINT { get; set; }
        public string FIRMA { get; set; }
        public System.Guid ID_SERVIZIO { get; set; }
        public System.Guid ID_GRUPPO { get; set; }
    }
}
