//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class vServiceGroup
    {
        public string GRUPPO_SERVIZIO { get; set; }
        public string CODE { get; set; }
        public string ENDPOINT { get; set; }
        public string FIRMA { get; set; }
        public System.Guid ID_SERVIZIO { get; set; }
        public System.Guid ID_GRUPPO { get; set; }
    }
}
