//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUserPermission
    {
        public System.Guid ID_USER { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public System.Guid ID_PROFILE { get; set; }
        public string PROFILO { get; set; }
        public string MENU { get; set; }
        public System.Guid MENU_ID { get; set; }
        public System.Guid ID_LANGUAGE { get; set; }
        public string LANGUAGE { get; set; }
    }
}
