//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUserPermission
    {
        public System.Guid ID_USER { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public System.Guid ID_PROFILE { get; set; }
        public string PROFILO { get; set; }
        public string MENU { get; set; }
        public System.Guid MENU_ID { get; set; }
        public System.Guid ID_LANGUAGE { get; set; }
        public string LANGUAGE { get; set; }
    }
}
